const $=s=>document.querySelector(s);
const S={endpoint:localStorage.getItem("orreryEndpoint")||"",rec:null,listening:false,busy:false,visualStarted:false};
function tick(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",hour12:false});$("#date").textContent=d.toLocaleDateString("en-US",{month:"short",day:"2-digit",year:"numeric"}).toUpperCase()}setInterval(tick,300);tick();
async function weather(){try{const r=await fetch("https://api.open-meteo.com/v1/forecast?latitude=33.5902&longitude=130.4017&current=temperature_2m,relative_humidity_2m,weather_code&timezone=Asia%2FTokyo"),j=await r.json(),c=j.current.weather_code,t=Math.round(j.current.temperature_2m),i=c===0?"☼":c<60?"☁":"◌",d=c===0?"CLEAR":c<60?"CLOUDY":"PRECIP";$("#temp").textContent=t+"°";$("#weatherIcon").textContent=i;$("#weatherText").textContent=d;$("#wTemp").textContent=t+"°";$("#wDesc").textContent=d;$("#humidity").textContent=j.current.relative_humidity_2m+"%"}catch(e){$("#weatherText").textContent="OFFLINE"}}weather();
function state(a,b){$("#listenLabel").textContent=a;$("#subLabel").textContent=b;$("#mode").textContent=a;$("#talkState").textContent=a==="STANDBY"?"PRESS TO TALK":"AI "+a;$("#systemState").textContent=a==="STANDBY"?"● ONLINE":"● "+a;$("#audioState").textContent=a==="STANDBY"?"IDLE":a;$("#voiceStatus").textContent=a==="STANDBY"?"READY":a;$("#activityText").textContent=a}
function msg(w,t){const e=document.createElement("div");e.className="msg "+w;e.innerHTML='<b>'+(w==="ai"?"O":"Y")+'</b><div><small>'+(w==="ai"?"ORRERY":"YOU")+'</small><p></p></div>';e.querySelector("p").textContent=t;$("#messages").appendChild(e);$("#messages").scrollTop=99999}
function speak(t){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="ja-JP";u.rate=.98;u.onstart=()=>state("SPEAKING","AI VOICE OUTPUT");u.onend=()=>state("STANDBY","PRESS TO TALK");speechSynthesis.speak(u)}
function local(t){if(/天気|気温|福岡/.test(t))return"福岡の現在の天気は画面に表示しています。AIリンクを接続すると、詳しい予報も会話できます。";if(/時間/.test(t))return"現在時刻は"+$("#clock").textContent+"です。";if(/自己紹介/.test(t))return"私はORRERY。あなたのiPhone上で動くAIアシスタントです。";if(/こんにちは|こんばんは|おはよう/.test(t))return"こんにちは。ORRERYはオンラインです。";return"現在はローカル会話モードです。LINK設定からAIバックエンドを接続すると、自由会話ができます。"}
async function ask(t){if(!t||S.busy)return;S.busy=true;$("#preview").textContent=t;msg("user",t);state("PROCESSING","ORRERY AI IS THINKING");let a="";try{if(S.endpoint){const r=await fetch(S.endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t})});if(!r.ok)throw Error(r.status);const j=await r.json();a=j.reply||j.output||j.message||"応答を取得できませんでした。"}else a=local(t)}catch(e){a="AIリンクに接続できませんでした。LINK設定のURLを確認してください。"}msg("ai",a);S.busy=false;speak(a)}
function setupSpeech(){const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C)return null;const r=new C;r.lang="ja-JP";r.continuous=false;r.interimResults=true;r.onstart=()=>{S.listening=true;$("#mic").classList.add("active");state("LISTENING","お話しください");visual()};r.onresult=e=>{let f="";for(let i=e.resultIndex;i<e.results.length;i++){const x=e.results[i][0].transcript;$("#preview").textContent=x;if(e.results[i].isFinal)f+=x}if(f)ask(f)};r.onerror=()=>{S.listening=false;$("#mic").classList.remove("active");state("STANDBY","マイクを確認してください")};r.onend=()=>{S.listening=false;$("#mic").classList.remove("active");if(!S.busy)state("STANDBY","PRESS TO TALK")};return r}S.rec=setupSpeech();
function visual(){if(S.visualStarted)return;S.visualStarted=true;const c=$("#viz"),x=c.getContext("2d");function resize(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio}resize();addEventListener("resize",resize);function draw(){const w=c.width,h=c.height;x.clearRect(0,0,w,h);x.beginPath();x.strokeStyle="#5ceaff";x.lineWidth=2*devicePixelRatio;const active=S.listening||speechSynthesis.speaking;for(let p=0;p<w;p+=4){const y=h/2+(active?Math.sin(p/16+Date.now()/80)*14+Math.sin(p/6+Date.now()/130)*5:Math.sin(p/28+Date.now()/500)*2);p?x.lineTo(p,y):x.moveTo(p,y)}x.stroke();$("#core").style.transform=active?`scale(${1+Math.sin(Date.now()/100)*.018})`:"scale(1)";requestAnimationFrame(draw)}draw()}
$("#mic").onclick=()=>{if(!S.rec){ask($("#preview").textContent);return}if(S.listening)S.rec.stop();else S.rec.start()};
$("#send").onclick=()=>{const t=$("#preview").textContent.trim();if(t&&t!=="オレリーに話しかけてください")ask(t)};
document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>ask(b.dataset.prompt));
$("#config").onclick=()=>{$("#endpoint").value=S.endpoint;$("#settings").showModal()};
$("#close").onclick=()=>$("#settings").close();
$("#save").onclick=()=>{S.endpoint=$("#endpoint").value.trim();localStorage.setItem("orreryEndpoint",S.endpoint);$("#aiLink").textContent=S.endpoint?"SECURE":"LOCAL";$("#settings").close();msg("ai",S.endpoint?"AIセキュアリンクを設定しました。":"ローカルモードに戻しました。")};
$("#clear").onclick=()=>{$("#messages").innerHTML="";msg("ai","セッションをリセットしました。システムオンライン。")};
$("#network").textContent=navigator.onLine?"ONLINE":"OFFLINE";addEventListener("online",()=>$("#network").textContent="ONLINE");addEventListener("offline",()=>$("#network").textContent="OFFLINE");if(S.endpoint)$("#aiLink").textContent="SECURE";state("STANDBY","PRESS TO TALK");visual();